:page-layout: standard_toc
:page-title: Year 10 IST - Common Test
:icons: font

= Year 10 IST - Common Test =

*Weight:* 20% +
*IT1001:* Monday 7 Jun 2021 (Week 17), Period 4 +
*IT1002:* Monday 7 Jun 2021 (Week 17), Period 1

== Changelog ==

This task was last updated on *Monday 24 May 2021*.

If any changes are made to the task they will be itemised here for ease of identification.

== Task Description ==

* This is a 20 question online multiple-choice quiz.
* You will have 45 minutes to complete the quiz.
* The quiz can potentially cover all content that has been completed throughout Semester One, but the primary focus is on binary exploitation.
* Some questions may require you to answer specific facts, and other questions may require problem-solving. Additionally, you may be provided with a binary and need to interrogate the binary using x32dbg to determine the answer to the question - so you must ensure that you have Windows on your computer along with x32dbg installed.
* The test is completely open-resource. Any resources (including the internet, past activities, handwritten or electronic notes) may be used. However, email and any other form of real-time (or near real-time) communication must not be used - while students can use resources to research how to solve the questions they may not communicate with anyone else during the test.
* Keep in mind that even though this test is open-resource, it is essential that all students undertake sufficient revision. Referring to other resources is only useful if you need to quickly reference or look-up something. If you do not already have a firm grasp of the cybersecurity concepts and tools then you cannot expect to research and understand completely new concepts, then answer the questions, in order to complete this task within the time frame.

== Outcomes to be Assessed ==

* *ACTDIK034:* Investigate the role of hardware and software in managing, controlling and securing the movement of and access to data in networked digital systems.
* *ACTDIP036:* Develop techniques for acquiring, storing and validating quantitative and qualitative data from a range of sources, considering privacy and security requirements.
* *ACTDIP040:* Design algorithms represented diagrammatically and in structured English and validate algorithms and programs through tracing and test cases.
* *ACTDIP041*: Implement modular programs, applying selected algorithms and data structures including using an object-oriented programming language.


== Context for the Task ==

The focus of this task is to allow students to demonstrate their level of skill and knowledge in cybersecurity.

== Hints and Pro Tips ==

Here you can find various hints and tips to help with your preparation for the common test.

* If you have been able to do all the activities and assignments we have completed throughout this semester, and have a firm grasp of the concepts underpinning these tasks, then you should feel quite comfortable with that level of knowledge going into the quiz.
* Should you have found any of these tasks challenging, or have been unable to complete them, then I strongly encourage you to go back and review those tasks. Don't forget that all the lessons for binary exploitation have video recordings which you can review.
