:page-layout: standard_toc
:page-title: Unit Outline and Assessment Schedule

= Year 10 IT &mdash; Semester One 2019

== Unit Outline and Assessment Schedule

=== Report Criteria / Areas of Learning

* Demonstrating a good understanding of Linux-based command line interfaces
* Understanding and effectively using the Vim text editor
* Understanding and writing ES6-compliant JavaScript code
* Demonstrating a good knowledge of the core Node.JS concepts including routing, templating, and model-view-controller
* Demonstrating sufficient overall knowledge of Node.JS to effectively write an entire working program
* Including sufficient comments and other intrinsic documentation, such as appropriate variable naming, to explain the purpose of the code

=== Assessment Schedule

include::semester_one_2019_table.adoc[]

=== Course Detail

* Introduction to the Linux CLI
* Introduction to Vim
* JavaScript ES6 Syntax
* Introduction to Node.JS
* Writing Node.JS Web Apps

=== Grade Allocation

[cols="1,20"]
|===

^.^|*A*
.^|Indicates that a student has demonstrated excellent achievement of what is expected.

^.^|*B*
.^|Indicates that a student has demonstrated high achievement of what is expected.

^.^|*C*
.^|Indicates that a student has demonstrated satisfactory achievement of what is expected. This student is achieving at the predicted level for the subject.

^.^|*D*
.^|Indicates that a student has demonstrated partial achievement of what is expected.

^.^|*E*
.^|Indicates that a student has demonstrated limited achievement of what is expected.

^.^|*S*
.^|Awarded to students who have been unable to complete sufficient work due to an extended period of illness or other approved absence (status).

|===

=== Absence from Class

It is your responsibility to catch up on work missed when absent from class. We suggest you email your teacher on the day you are away to request any missed work or information.

If you are away for an assessment, please consult your teacher to make arrangements to complete the assessment as soon as possible after you return to school. After 10 school days, the assessment cannot be rescheduled and either an estimate (in the case of an explained absence) or a zero will be awarded.

For assignments and non-test events a late work penalty of 10% of the total possible mark will be incurred for each day late if work is not submitted on the due date.  A loss of 30% is incurred if work due on a Friday is not submitted until the following Monday. After one week (7 days) the item will be awarded a mark of zero.

=== All My Own Work

Please note that any submitted work is to be your own. There are serious consequences for submitting work which is taken from another person, even if they give it to you voluntarily. To decide if you have written the material, we may need to question you about your understanding of the topic. Please be careful when presenting ideas which are not entirely your own; reference such material thoroughly.

For more specific examples, see the <<course_overview/course_overview.adoc#academic-honesty, Academic Honesty>> section of the Course Outline.
