:page-layout: standard_toc
:page-title: Year 10 IST - Common Test
:icons: font

= Year 10 IST - Common Test =

*Weight:* 30% +
*Date:* Wednesday 1 November 2017 (Week 14)

== Changelog ==

This task was last updated on *Sunday 1 October 2017*.

If any changes are made to the task they will be itemised here for ease of identification.

== Task Description ==

* Students will have 45 minutes to complete the task during their normal class time on Wednesday 1 November 2017.
* This will be similar to the Semester One Take Home Common Test: students will be provided with a semi-complete Xcode project which needs to be finished to get into a fully working state. The task will be such that it can be achieved within the 45 minute time limit by a student who knows the required content.
* All students must ensure that their laptop is fully charged, working, and has the latest version of Xcode installed to complete the task. Internet access is also strongly recommended.
* Your code in the test does not need to be commented. However, proper naming of variables (to reflect their purpose) is required, along with correct indentation of code.
* In preparation for this task, students should review all concepts relating to Swift and iOS programming that we have covered during Term One, Assignment One, and Assignment Two. This includes, but is not limited to, loops, if statements, actions, outlets, functions, objects, optionals, etc. The level of the content being examined is more advanced than the Semester One Common Test, but does not include any new topics (as everyone is doing something different for their Semester Two project, so we cannot examine any specific new topics).
* The test is completely open-resource. Any resources (including the internet, textbooks, handwritten or electronic notes) may be used. However, email and any other form of real-time (or near real-time) communication must not be used - while students can use resources to research how to solve the questions they may not communicate with anyone else during the test.
* Keep in mind that even though this test is open-resource, it is essential that all students undertake sufficient revision. Referring to other resources is only useful if you need to quickly reference or look-up something. If you do not already have a firm grasp of Swift and iOS development then you cannot expect to research and understand completely new concepts, then answer the questions, in order to complete this task within the timeframe.

== Outcomes to be Assessed ==

* 5.1.1 selects and justifies the application of appropriate software programs to a range of tasks
* 5.2.1 describes and applies problem-solving processes when creating solutions
* 5.2.2 designs, produces and evaluates appropriate solutions to a range of challenging problems

== Context for the Task ==

The focus of this task is to allow students to demonstrate their level of Swift and iOS development.

== Hints and Pro Tips ==

Here you can find various hints and tips to help with your preparation for the common test.

* It is highly advisable that you create some kind of notes page (also known as a "cheat-sheet") and/or electronic versions of common code (with an explanation as to their purpose). This will provide a extremely valuable and quick reference for you during the test, saving you from having to search through your book or online. It also has the added benefit that by compiling this information you will essentially be revising all these items!
* Use Post-It tabs to put tabs throughout your textbook (or virtual post it notes, in the case of the PDF text book) allowing you quick and easy reference to particularly important sections of your book.
